### ISSUE TITLE
CF 无效果 yolo检测无效果

### ISSUE THREAD

**Issue by BanSheng-admin** [chaoyu1999/FPSAutomaticAiming#12]
请问是模型原因么？我模型已经换了CF的模型 作者大佬可以解答下么？

**Comment by BanSheng-admin** [comment]
是还需要修改其他文件么？第一次接触yolo 不是很清楚

**Comment by chaoyu1999** [comment]
啊这。。。我预训练模型是cs的，你找几张cs的人物图试试

**Comment by BanSheng-admin** [comment]
试了下  CSGO是可以的  那可能是直接把csgo模型换成cf的模型不行的么？你看我要需改哪里么？

**Comment by chaoyu1999** [comment]
cf 的模型是yolov5s的模型吗？，如果不是的话就不行，得重新训练

**Comment by chaoyu1999** [comment]
cf 的模型是yolov5的模型吗？不是的话就得重新训练

**Comment by BanSheng-admin** [comment]
可以了 但是瞄准的人物不是头部。。瞄准位置在腰部 请问这是模型原因还是哪里问题尼？

**Comment by BanSheng-admin** [comment]
看了下应该是模型问题   易键鼠调用 dll模块找不到   看了下别人的提问  自己封装的那个貌似删除了

**Comment by chaoyu1999** [comment]
> 可以了 但是瞄准的人物不是头部。。瞄准位置在腰部 请问这是模型原因还是哪里问题尼？

那就是cf 的模型有问题

**Comment by chaoyu1999** [comment]
> 看了下应该是模型问题 易键鼠调用 dll模块找不到 看了下别人的提问 自己封装的那个貌似删除了

那个封装dll的项目在之前的旧版本里，我上周末把旧版的项目给删了，上传了最新版的项目

**Comment by BanSheng-admin** [comment]
好的   我去研究研究 
![图片](https://user-images.githubusercontent.com/67738995/144956775-e739353c-4a11-4a9e-be7a-51fe491f500d.png)
这个train 和val分别指 的是？

**Comment by chaoyu1999** [comment]
> 好的 我去研究研究 ![图片](https://user-images.githubusercontent.com/67738995/144956775-e739353c-4a11-4a9e-be7a-51fe491f500d.png) 这个train 和val分别指 的是？
images下的train和val分别是训练和验证所需的图片数据；labels下的train和val分别是images中对应的
标签数据。

**Comment by BanSheng-admin** [comment]
好的  我现在还在想办法解决鼠标移动问题，我调用罗技dll会出现鼠标移动到别处的现象，易键鼠还是dll找不到，裂开了

**Comment by BanSheng-admin** [comment]
重新封装了依旧找不到dll

**Comment by chaoyu1999** [comment]
> 重新封装了依旧找不到dll
那可能是dll路径什么的有问题吧

**Comment by BanSheng-admin** [comment]
路径没问题啊...大佬可以加个联系方式么

**Comment by chaoyu1999** [comment]
> 路径没问题啊...大佬可以加个联系方式么

有编程基础的话多调试调试，应该可以调好的。联系方式就在github上交流吧，其它的不方便给

**Comment by BanSheng-admin** [comment]
好的  
![图片](https://user-images.githubusercontent.com/67738995/144979505-cd010a73-5444-4e80-9514-cc47c687323d.png)
我这样是没问题的  没有报错 但是鼠标不动了。。。我再去调试下 哈哈

**Comment by chaoyu1999** [comment]
> 好的 我现在还在想办法解决鼠标移动问题，我调用罗技dll会出现鼠标移动到别处的现象，易键鼠还是dll找不到，裂开了

鼠标乱移：可能是游戏里面的鼠标灵敏度太高了

**Comment by BanSheng-admin** [comment]
不是乱移动 是直接不移动了 😂

**Comment by BanSheng-admin** [comment]
![图片](https://user-images.githubusercontent.com/67738995/144980612-0703a184-0f63-4885-b2b3-24c35c7e1e48.png)
不知道为什么这样又可以了 但是鼠标移动没效果

**Comment by chaoyu1999** [comment]
> ![图片](https://user-images.githubusercontent.com/67738995/144980612-0703a184-0f63-4885-b2b3-24c35c7e1e48.png) 不知道为什么这样又可以了 但是鼠标移动没效果

这个是我当时封装易键鼠dll的项目，可以看看对你有帮助没https://github.com/chaoyu1999/FPSAutomaticAiming/blob/main/lib/dll%E5%B0%81%E8%A3%85%E9%A1%B9%E7%9B%AE.zip

**Comment by chaoyu1999** [comment]
易键鼠官方给的dll在64位pyhton 下无法正常调用，但在C语言下可以正常调用。主要是要将```HANDLE m_hdl = M_Open(1);```这个变量弄成全局变量才可以。
![image](https://user-images.githubusercontent.com/46945475/144981504-6ff5b06a-6201-48d0-93df-0980faf9de42.png)

**Comment by BanSheng-admin** [comment]
64位是无法正常调用么。。。那我换下32试一下 我是64位

**Comment by chaoyu1999** [comment]
> 64位是无法正常调用么。。。那我换下32试一下 我是64位

32位pyhton的话神经网络就无法运行了

**Comment by chaoyu1999** [comment]
> 64位是无法正常调用么。。。那我换下32试一下 我是64位

所以我才自己封装了个64位python能调用的dll

**Comment by BanSheng-admin** [comment]
这。。。我现在是鼠标移动无效果  重新打包也是一样的  我重新打包用的就是你的旧版本里的

**Comment by chaoyu1999** [comment]
> 这。。。我现在是鼠标移动无效果 重新打包也是一样的 我重新打包用的就是你的旧版本里的

啊这。。。你把检测到的坐标print一下看到底是检测出问题了，还是移动鼠标出问题了

**Comment by BanSheng-admin** [comment]
貌似又好了 真是玄学  我去游戏里面测试一下

**Comment by chaoyu1999** [comment]
> 貌似又好了 真是玄学 我去游戏里面测试一下

还可以试试管理员身份运行。如果还不行，就单独开个项目把鼠标移动测试好再用。

**Comment by BanSheng-admin** [comment]
不行   。。。好的 我去测试下

**Comment by BanSheng-admin** [comment]
还是不可以 裂开了 谢谢大佬解答这么多疑惑  我自己去研究研究测试吧 谢啦

**Comment by chaoyu1999** [comment]
> 还是不可以 裂开了 谢谢大佬解答这么多疑惑 我自己去研究研究测试吧 谢啦

加油

**Comment by BanSheng-admin** [comment]
还是不行  大佬请问为什么用罗技
![图片](https://user-images.githubusercontent.com/67738995/144989244-c9ad166c-b7a5-4b30-a383-e2401774737a.png)
这样移动鼠标会一直往右下方移动 跟pyautogui.moveRel的移动效果是一样的

**Comment by BanSheng-admin** [comment]
行吧 一个相对移动 一个移动到。。。。裂开   不知道怎么转化

**Comment by BanSheng-admin** [comment]
易键鼠是需要购买盒子么？

**Comment by chaoyu1999** [comment]
> 这样移动鼠标会一直往右下方移动 跟pyautogui.moveRel的移动效果是一样的

是

**Comment by chaoyu1999** [comment]
> 还是不行 大佬请问为什么用罗技 ![图片](https://user-images.githubusercontent.com/67738995/144989244-c9ad166c-b7a5-4b30-a383-e2401774737a.png) 这样移动鼠标会一直往右下方移动 跟pyautogui.moveRel的移动效果是一样的

我的代码里的坐标是绝对移动，要用相对移动可以自己换算一下。

**Comment by BanSheng-admin** [comment]
我正在研究怎么换算😂感觉有点麻烦

**Comment by BanSheng-admin** [comment]
大佬 后期还会更新么

**Comment by BanSheng-admin** [comment]
大佬后期还会更新么。。。。

**Comment by chaoyu1999** [comment]
> 大佬后期还会更新么。。。。

看情况，有空的话会再完善下的

**Comment by BanSheng-admin** [comment]
我已经改完了，可以用了，就是人多乱抖严重，还有cf全屏下检测不理想，谢谢大佬分享源码，学习到了
